;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Crouch",DevComment="")
+GameplayTagList=(Tag="Ability.Crouch.End",DevComment="")
+GameplayTagList=(Tag="Ability.CrouchSlide",DevComment="")
+GameplayTagList=(Tag="Ability.CrouchSlide.End",DevComment="")
+GameplayTagList=(Tag="Ability.Dash",DevComment="")
+GameplayTagList=(Tag="Ability.Dash.RegenCharge",DevComment="")
+GameplayTagList=(Tag="Ability.Fire",DevComment="")
+GameplayTagList=(Tag="Ability.Jump",DevComment="")
+GameplayTagList=(Tag="Ability.Vaulting",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.DashCount",DevComment="")
+GameplayTagList=(Tag="Data.HealAmount",DevComment="")
+GameplayTagList=(Tag="Data.JumpCount",DevComment="")
+GameplayTagList=(Tag="Data.MaxHealth",DevComment="")
+GameplayTagList=(Tag="Data.weaponCooldown",DevComment="")
+GameplayTagList=(Tag="Input.PrimaryAction",DevComment="")
+GameplayTagList=(Tag="Input.PrimaryAction.stop",DevComment="")
+GameplayTagList=(Tag="State.Coma",DevComment="")
+GameplayTagList=(Tag="State.Dashing",DevComment="")
+GameplayTagList=(Tag="State.Firing",DevComment="")
+GameplayTagList=(Tag="State.Firing.FiringCooldown",DevComment="")
+GameplayTagList=(Tag="State.Jumping",DevComment="")
+GameplayTagList=(Tag="State.Movement.Landed",DevComment="")

